sudo: required
os:
  - linux
services:
  - docker
language: go

env:
- GO111MODULE=on

go:
  - 1.11.5

jobs:
  include:
    - stage: build
      script: make build
    - stage: check
      script: make check
    - stage: unit-test
      script: make unit-test
    - stage: deploy
      script: make deploy
      if: tag =~ ^v\d
