
sudo: required

#language: ruby

services:
  - docker

#before_install:
#- docker pull carlad/sinatra
#- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#- docker ps -a
#- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#- bundle exec rake test


language: go

env:
  global:
    - PLUGIN_NAME_ROOTFS=docker-volume-linode:rootfs-${TRAVIS_BUILD_NUMBER}
    - PLUGIN_NAME=docker-volume-linode:${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - docker build --no-cache -q -t ${PLUGIN_NAME_ROOTFS} .
  - mkdir -p ./plugin/rootfs
  - docker create --name tmp  ${PLUGIN_NAME_ROOTFS}
  - docker export tmp | tar -x -C ./plugin/rootfs
  - cp config.json ./plugin/
  - docker rm -vf tmp
  - docker plugin rm -f ${PLUGIN_NAME} || true
  - docker plugin create ${PLUGIN_NAME} ./plugin

script:
  - docker plugin push ${PLUGIN_NAME}

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

